# Generated by Django 4.0.4 on 2022-06-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('secondname', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
