# Generated by Django 4.0.4 on 2022-06-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0002_manager_alter_student_firstname_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='banned_manager',
            field=models.ManyToManyField(null=True, related_name='banned_students', to='devman.manager', verbose_name='Нежелательные ПМ'),
        ),
        migrations.AddField(
            model_name='student',
            name='banned_student',
            field=models.ManyToManyField(null=True, related_name='banned_colleagues', to='devman.student', verbose_name='Нежелательные члены команды'),
        ),
        migrations.AddField(
            model_name='student',
            name='desired_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devman.manager', verbose_name='Желаемый ПМ'),
        ),
        migrations.AddField(
            model_name='student',
            name='desired_student',
            field=models.ManyToManyField(null=True, related_name='desired_colleagues', to='devman.student', verbose_name='Обязательные партнеры в команде'),
        ),
    ]
