# Generated by Django 4.0.4 on 2022-06-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0003_student_banned_manager_student_banned_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='banned_manager',
            field=models.ManyToManyField(blank=True, related_name='banned_students', to='devman.manager', verbose_name='Нежелательные ПМ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='banned_student',
            field=models.ManyToManyField(blank=True, related_name='banned_colleagues', to='devman.student', verbose_name='Нежелательные члены команды'),
        ),
        migrations.AlterField(
            model_name='student',
            name='desired_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devman.manager', verbose_name='Желаемый ПМ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='desired_student',
            field=models.ManyToManyField(blank=True, related_name='desired_colleagues', to='devman.student', verbose_name='Обязательные партнеры в команде'),
        ),
    ]
