# Generated by Django 4.0.4 on 2022-06-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0004_alter_student_banned_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='banned_student',
            field=models.ManyToManyField(blank=True, to='devman.student', verbose_name='Нежелательные члены команды'),
        ),
        migrations.AlterField(
            model_name='student',
            name='desired_student',
            field=models.ManyToManyField(blank=True, to='devman.student', verbose_name='Обязательные партнеры в команде'),
        ),
    ]
