# Generated by Django 4.0.4 on 2022-06-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0005_alter_student_banned_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата начала проекта')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название проекта')),
                ('call_time', models.TimeField(blank=True, null=True, verbose_name='Время созвона')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devman.manager', verbose_name='ПМ')),
                ('students', models.ManyToManyField(related_name='teams', to='devman.student', verbose_name='Студенты')),
            ],
        ),
    ]
