# Generated by Django 4.0.4 on 2022-06-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='far_east',
            field=models.BooleanField(default=False, verbose_name='С Дальнего Востока'),
        ),
    ]
