# Generated by Django 4.0.4 on 2022-06-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0007_student_far_east'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='available_time_finish',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='available_time_start',
            field=models.TimeField(null=True),
        ),
    ]
