# Generated by Django 4.0.4 on 2022-06-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0008_student_available_time_finish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'ПМ', 'verbose_name_plural': 'ПМы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Новичок', 'Новичок'), ('Новичок +', 'Новичок +'), ('Джун', 'Джун')], default='Новичок', max_length=10, verbose_name='Уровень подготовки'),
        ),
    ]
