# Generated by Django 4.0.4 on 2022-06-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0009_alter_manager_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='final_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Результат проекта'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Проект активен'),
        ),
    ]
