# Generated by Django 4.0.4 on 2022-06-02 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0010_team_final_status_team_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tg_chat',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Чат в Телеграм'),
        ),
        migrations.AddField(
            model_name='team',
            name='trello',
            field=models.URLField(blank=True, null=True, verbose_name='Доска в Трелло'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ts', to='devman.manager', verbose_name='ПМ'),
        ),
    ]
