# Generated by Django 4.0.4 on 2022-06-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0011_team_tg_chat_team_trello_alter_team_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Работает'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступен для проекта'),
        ),
    ]
