# Generated by Django 4.0.4 on 2022-06-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0012_manager_is_active_student_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='banned_student',
            new_name='banned_students',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='desired_student',
            new_name='desired_students',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Новичок', 'novice'), ('Новичок +', 'novice+'), ('Джун', 'junior')], default='no_project', max_length=25, verbose_name='Текущий статус'),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.URLField(blank=True, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Новичок', 'novice'), ('Новичок +', 'novice+'), ('Джун', 'junior')], default='novice', max_length=10, verbose_name='Уровень подготовки'),
        ),
    ]
