# Generated by Django 4.0.4 on 2022-06-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0013_rename_banned_student_student_banned_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='secondname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='secondname',
        ),
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(blank=True, max_length=70, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=70, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('novice', 'Новичок'), ('novice+', 'Новичок +'), ('junior', 'Джун')], default='novice', max_length=10, verbose_name='Уровень подготовки'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('no_project', 'Нет проекта'), ('awaiting_answer', 'В ожидании ответа'), ('awaiting_team', 'Ждет команду'), ('in_project', 'В проекте'), ('declined_project', 'Не сможет участвовать')], default='no_project', max_length=25, verbose_name='Текущий статус'),
        ),
    ]
