# Generated by Django 4.0.4 on 2022-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0014_remove_manager_firstname_remove_manager_secondname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='project_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала ближайшего проекта'),
        ),
    ]
