# Generated by Django 4.0.4 on 2022-06-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0016_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_date', models.DateField(verbose_name='Основная неделя проекта')),
                ('secondary_date', models.DateField(verbose_name='Запасная неделя проекта')),
                ('is_active', models.BooleanField(verbose_name='Даты активны')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='available_time_finish',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='available_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
