# Generated by Django 4.0.4 on 2022-06-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0017_start_alter_student_available_time_finish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='start',
            name='is_active',
        ),
        migrations.AddField(
            model_name='start',
            name='send_request',
            field=models.BooleanField(default=False, verbose_name='Отправить запрос'),
        ),
        migrations.AddField(
            model_name='start',
            name='send_teams',
            field=models.BooleanField(default=False, verbose_name='Разослать сформированные команды'),
        ),
        migrations.AddField(
            model_name='student',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор чата с ботом в ТГ'),
        ),
    ]
